// DATA TYPES

//WE HAVE TWO (2) DATA TYPES IN JAVASCRIPT
// 1) PRIMITIVE DATA TYPE
// 2) REFERENCE DATA TYPE


// FIVE (5) TYPES OF PRIMITIVE DATA TYPE

// 1) STRING 2) NUMBER 3) BOOLEAN 4) NULL  5) UNDEFINED


